defaults:
  - _self_
  - task: square_image
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: train_action_chunk_transformer
_target_: diffusion_policy.workspace.train_action_chunk_transformer_workspace.TrainActionChunkTransformerWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 10
n_obs_steps: 1
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_cond: True

policy:
  _target_: diffusion_policy.policy.action_chunk_transformer_policy.ActionChunkTransformerPolicy

  use_dp_vis: False
  joiner:
    _target_: diffusion_policy.model.ACT.backbone.Joiner
    backbone:
      _target_: diffusion_policy.model.ACT.backbone.Backbone
      name: resnet18
      train_backbone: True
      return_interm_layers: False
      dilation:  False
    position_embedding:
      _target_: diffusion_policy.model.ACT.position_encoding.PositionEmbeddingSine
      num_pos_feats: ${eval:'${policy.transformer.d_model} // 2'}
      temperature: 10000
      normalize: False
      scale: null

  num_encoder_layers: 5
  
  trans_encoder_layer:
    _target_: diffusion_policy.model.ACT.transformer.TransformerEncoderLayer
    d_model: 256
    nhead: 8
    dim_feedforward: ${eval:'${policy.trans_encoder_layer.d_model} * 4'}
    dropout: 0.1
    activation: relu
    normalize_before: False

  transformer:
    _target_: diffusion_policy.model.ACT.transformer.Transformer
    d_model: 256
    nhead: 8
    num_encoder_layers: 5
    num_decoder_layers: 5
    dim_feedfowrard: ${eval:'${policy.transformer.d_model} * 4'}
    dropout: 0.1
    activation: relu
    normalize_before: False
    return_intermediate_dec: False
  
  num_queries: ${horizon}
  kl_weight: 10
  latent_dim: 32
  hidden_dim: ${policy.transformer.d_model}
  
  shape_meta: ${shape_meta}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  crop_shape: [76, 76]
  obs_encoder_group_norm: True
  eval_fixed_crop: True
  temporal_agg: True

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  # Transformer needs lr wormup
  lr_warmup_steps: 500
  num_epochs: 1001
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epcoch
  rollout_every: 20
  checkpoint_every: 50
  val_every: 1
  sample_every: 1
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

optimizer:
  weight_decay: 1.0e-4
  learning_rate: 1.0e-4
  lr_backbone: 1.0e-5

dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: False
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: False
  pin_memory: True
  persistent_workers: False

logging:
  project: square_100
  resume: False
  mode: online
  name: act
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: val_loss
    mode: min
    k: 5
    format_str: 'epoch={epoch:04d}-val_loss={val_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/2024.02.19/15.31.01_train_action_chunk_transformer_real_pick_image
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/2024.02.19/15.31.01_train_action_chunk_transformer_real_pick_image
  sweep:
    dir: data/outputs/2024.02.19/15.31.01_train_action_chunk_transformer_real_pick_image
    subdir: ${hydra.job.num}